weather_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', 'postgres') }}"
      user: "{{ env_var('DB_USER', 'weather_user') }}"
      password: "{{ env_var('DB_PASSWORD', 'weather_pass') }}"
      port: "{{ env_var('DB_PORT', '5432') | int }}"
      dbname: "{{ env_var('DB_NAME', 'weather_db') }}"
      schema: staging
      threads: 4
      keepalives_idle: 0
      search_path: "staging,marts,raw,public"
    
    prod:
      type: postgres
      host: "{{ env_var('DB_HOST') }}"
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASSWORD') }}"
      port: "{{ env_var('DB_PORT') | int }}"
      dbname: "{{ env_var('DB_NAME') }}"
      schema: staging
      threads: 4
      keepalives_idle: 0
      search_path: "staging,marts,raw,public"